### ISSUE TITLE
TypeError: getViewBounds is not a function

### ISSUE THREAD

**Issue by danilovaz** [pzuraq/liquid-tether#70]
`Liquid-Tether: 2.0.0` doesn't works with `Ember 2.9.0`

I'm also update to `Liquid-Fire: 0.26.4`

When click popup/popover get this error: `TypeError: getViewBounds is not a function`

**Comment by pzuraq** [comment]
Interesting, I'll dive into this asap. Seems like it could be a pretty big issue.

**Comment by danilovaz** [comment]
Yes, I think so. I'll try to do some tests too.

**Comment by pzuraq** [comment]
Yeah, so this seems to just be a bug in liquid-fire v0.26.1

https://github.com/ember-animation/liquid-fire/issues/510

Updating to the latest should fix it, I'm making a PR that does that for the repo
